default: &default
  adapter: postgresql
  username: postgres
  password: postgres
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: abacus_development

test:
  <<: *default
  database: abacus_test

production:
  <<: *default
  database: abacus_production
  username: deploy
  password: <%= ENV['ABACUS_DATABASE_PASSWORD'] %>